dist: trusty
sudo: required

language: php

php:
  - 5.6

services:
  - docker

cache:
  apt: true
  directories:
    - $TRAVIS_BUILD_DIR/vendor
    - $TRAVIS_BUILD_DIR/tests/node_modules
    - $HOME/.composer/cache
    - ~/.npm
    - ~/.cache

env:
  matrix:
    - TEST_COUNTRY=brazil

#before_install:
#  - nvm install stable
#  - nvm use stable

install:
  - composer install
#  - cd $TRAVIS_BUILD_DIR/tests && npm ci
#  - cd $TRAVIS_BUILD_DIR

#script:
#  - bash ./tests/bin/test.sh

stages:
  - lint
#  - unit
#  - admin_tests
#  - test
  - release
  - deploy

jobs:
  include:
    - stage: lint
      env:
        - TEST_COUNTRY=
      script:
        - travis_wait bash ./.scripts/phpcs.sh
    - stage: unit
      env:
        - TEST_COUNTRY=
      script:
        - ./vendor/bin/phpunit
    - stage: admin_tests
      env:
        - TEST_COUNTRY=
      script:
        - bash ./tests/bin/admin-test.sh
    - stage: release
      script:
        - bash <(curl -s https://codecov.io/bash)
        - bash .scripts/before_deploy.sh
        - cd $TRAVIS_BUILD_DIR
        - zip -r /tmp/ebanx-local-payment-gateway-for-woocommerce ./* -x "*.git*" "*tests*" "*_vendor*"
      env:
        - TEST_COUNTRY=
      deploy:
        - provider: releases
          api_key:
            secure: change_this
          file: /tmp/ebanx-local-payment-gateway-for-woocommerce.zip
          skip_cleanup: true
          on:
            tags: true
            all_branches: true
    - stage: deploy
      script:
        - bash .scripts/before_deploy.sh
      env:
        - TEST_COUNTRY=
      deploy:
        - provider: script
          skip_cleanup: true
          script: ./deploy.sh
          on:
            tags: true
            all_branches: true
