version: '3.1'

services:
  woocommerce:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_HOST: mysql
      EBANX_STOREFRONT_THEME_VERSION: 2.6.0
      EBANX_ADMIN_USERNAME: ebanx
      EBANX_ADMIN_PASSWORD: ebanx
      EBANX_SITE_TITLE: EBANX Pay
      EBANX_SITE_EMAIL: plugin@ebanxpay.com
      WOOCOMMERCE_PLUGIN_VERSION: 4.4.1

      WOOCOMMERCE_URL: wclocal
      WOOCOMMERCE_EXTERNAL_PORT: 8080
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html/wp-content/plugins/woocommerce-gateway-ebanx-local
    links:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3307:3306
    volumes:
      - ./.data:/var/lib/mysql
